name: Deploy to Heroku

on:
  push:
    branches:
      - main # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker build --platform linux/amd64 -t registry.heroku.com/${HEROKU_APP_NAME}/web .
          docker push registry.heroku.com/${HEROKU_APP_NAME}/web

      - name: Set Heroku API key
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku config:set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --app ${HEROKU_APP_NAME}
      - name: Set SECRET_KEY and ALGORITHM env vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku config:set SECRET_KEY=${{ secrets.SECRET_KEY }} --app ${HEROKU_APP_NAME}
          heroku config:set ALGORITHM=${{ secrets.ALGORITHM }} --app ${HEROKU_APP_NAME}

      - name: Release image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku container:release web -a ${HEROKU_APP_NAME}
